### ISSUE TITLE
Can't post data with .Net 4.5.2

### ISSUE THREAD

**Issue by dchaib** [influxdata/influxdb-csharp#13] opened 2016-06-14 15:49 UTC
I am trying to use this library with projects running with .Net 4.5.2. I have made some very basic applications (a console application and an MVC website) inspired from the readme but none has been able to send the data to my server neither with the collector, nor with the raw API.

From what I have been able to find, it looks like the call to `PostAsync` in `LineProtocolClient` never ends or that it is not awaited successfully. I don't have any timeout or exception.

If I run the sample provided in the repository directly, it works fine.
If I copy the code from LineProtocol in my test application, it works fine as well.

**Comment by nblumhardt** [comment] 2016-06-14 21:53
Hi - that's very interesting, thanks for the report.

Have you run with "break on all exceptions" enabled in the debugger? It may help to catch anything that's otherwise slipping by unnoticed in the background. Guessing you have, but I can't think of much else to try at this point :)

Also, when you run the sample, it should have the option of running as either .NET Core or .NET 4.5.1 - do you get different results from either configuration?

**Comment by dchaib** [comment] 2016-06-15 08:56
Hi,
Breaking on all exceptions didn't give any more information.
I have tried to run the sample with .NET 4.5.1, but I failed :) The application crashes on startup, but I don't have time to read the error message. That is probably caused by a lack of experience with .NET Core though :)

**Comment by dchaib** [comment] 2016-07-20 15:02
I have found what line was causing the issue and a workaround... Not sure why this is happening though.

The application was blocking on line 31 of `HttpLineProtocolEmitter.cs`:
```cs
var influxResult = _client.WriteAsync(payload).Result;
```

The workaround consists in changing this line to:
```cs
var influxResult = _client.Write(payload);
```
and moving the async part to `LineProtocolClient`, inside a new Write method, that would simply change the post code to:
```cs
var response = _httpClient.PostAsync(endpoint, content, cancellationToken).Result;
```

Do you know why this happens? Would you mind if I submit this as a PR?

**Comment by nblumhardt** [comment] 2016-07-20 23:34
Hi - I'm not certain it's the cause, but the missing `ConfigureAwait()` calls fixed in #17 could be the cause of this.

Because it's hard to move forward at all on the old RC1 tooling I'm going to get #16 merged.

If you have a chance look over #17 we should be able to push that through and see if it makes any difference as well. All help appreciated :-)

**Comment by dchaib** [comment] 2016-07-21 07:21
Your proposition feels better than my workaround! :-) I'll have a look at it as soon as possible, hopefully in the next hours.

**Comment by dchaib** [comment] 2016-07-21 11:23
It looks like #17 fixed the issue! The data is sent correctly to InfluxDB and the rest of the code runs normally afterwards.

**Comment by nblumhardt** [comment] 2016-07-21 21:55
Brilliant, thanks for closing the loop.

**Closed by nblumhardt** 2016-07-21 21:55 UTC
